# Week 10 Homework
##### Please be sure your functions work for vectors with a size of three and matrices that are 3x3 and use appropriate error handling. Bonus points if you can further generalize them for larger vectors and matrices. 

In [103]:
from pylatex import Document, Section, Subsection, Tabular
from pylatex import Math, TikZ, Axis, Plot, Figure, Matrix, Alignat
from pylatex.utils import italic
import numpy as np
from numpy import linalg as la
import math

##### 1.	Explain the dot product and cross product in your own words in markdown. Use LaTeX to properly show the equations.

The dot product of two vectors is the sum of the products of the corresponding elements in the vectors.  It is a number that gives an indication of the extent to which two vectors move in the same direction.  Two vectors that run perpendicular to one another will have a dot product of zero.  Two vectors that overlap one another (and therefor move in exactly the same direction) will have a dot product equal to the parallel component of the magnitude of one vector in relation to the other multiplied by the magnitude of the other vector.

Unlike dot product, the cross product of two vectors yields another vector.  This vector runs perpendicular to each of the two vectors and, hence, perpendicular to the plane containing those vectors.  The magnitude of the cross product is equal to the magnitude of the perpendicular component of one vector multiplied by the magnitude of the second vector in its entirety.

$$\vec{A} \cdot \vec{B}=\left | \vec{A} \right |\left | \vec{B} \right |\cos\theta $$

$$\vec{A} \times \vec{B}=\left | \vec{A} \right |\left |\vec{B} \right |\sin\theta $$

##### 2.	Write a function angle_between(v1, v2) where v1 and v2 are two vectors that are passed in, and the angle between them is calculated. 

In [104]:
def angle_between(v1,v2):
    
    try:
        dotprod = np.dot(v1, v2)
        v1_mag = la.norm(v1)
        v2_mag = la.norm(v2)
        denom = v1_mag * v2_mag
        if denom == 0:
            print("Must use vectors with nonzero magnitude.  Cannot divide by zero.")
        else:    
            ratio = dotprod/denom
            if ratio < -1 or ratio > 1:
                print('Cosine value must be between -1 and 1 inclusive')
            else:
                theta = math.acos(ratio)
                print('The angle between the vectors is '+str(theta)+' radians.')        
    except Exception as e:
        print(e)

In [105]:
# Create two vectors to test the error handling
a = np.array([0, 0, 0, 0, 0])
b = np.array([9, 7, 5, 3, 1])

angle_between(a,b)

Must use vectors with nonzero magnitude.  Cannot divide by zero.


In [106]:
# Create two vectors to test the function's success
c = np.array([3, 5, 7, 9, 11])
d = np.array([9, 7, 5, 3, 1])

angle_between(c,d)

The angle between the vectors is 0.89880829982002 radians.


##### 3.	Write a function called row_dot(A, r1, r2) which takes an input matrix called A, one row number identified by r1, and another row number identified by r2 and returns the dot product of the r1 and r2 rows (indexing starts at 0).


In [107]:
def row_dot(A, r1, r2):
    try:
        #r1=r1-1
        #r2=r2-1
        if r1 < 0 or r2 < 0:
            print("Enter positive row numbers only.")
        else:
            dot=np.dot(A[r1-1],A[r2-1])
            print('The dot product of row',r1,' and row',r2,' is ',dot,'.')
    except Exception as e:
        print(e)

In [108]:
# Create matrix B to test function success
B = [[4,3,5,8],
     [-3,6,9,2],
     [0,2,-7,1],
     [-5,-1,-10,-3]]

row_dot(B,2,4)

The dot product of row 2  and row 4  is  -87 .


In [109]:
# Test error handling
row_dot(B,-2,2)

Enter positive row numbers only.


In [110]:
# Test error handling
row_dot(B,1,6)

list index out of range


##### 4.	Write a function matrix_division(m1, m2) that takes in two matrices, m1 and m2, and returns the result. What is the trick with matrix division?


In [145]:
def matrix_division(m1,m2):
    try:
        m1_inv = la.inv(m1) # for multiplication later
        m2_trans = np.transpose(m2) # for dot products later
        # Create a zero matrix to house the result. Dimensions are equal to the number of rows in matrix m1_inv and the number
        # of columns in matrix m2 (same as number of rows in m2 tranpose).
        quotient = np.zeros((len(m1_inv), len(m2_trans)))
        for i in range(len(m1)):
            for j in range(len(m2_trans)):
                quotient[i][j] = np.dot(m1_inv[i],m2_trans[j])
        print(quotient)
    except Exception as e:
        print(e)

In [147]:
M = np.array([[6,5,3,-7],
              [2,-1,2,-3],
              [-4,2,8,6],
              [3,-1,-9,-8]])

N = np.array([[4,9,-3,6,1,7],
              [-2,-3,-5,7,9,2],
              [3,-1,7,5,-2,-1],
              [-1,5,7,4,-4,-2]])

matrix_division(M,N)

[[-0.45545977 -0.46408046 -5.64224138 -3.70833333  1.83908046  1.65948276]
 [ 1.24568966  2.13362069  2.15086207 -0.375      -2.75862069  0.07327586]
 [-0.08333333 -0.58333333 -0.25        1.58333333  1.33333333  0.25      ]
 [-0.10775862 -0.40948276 -2.97844828 -3.625       0.03448276  0.58189655]]


##### 5.	Write a function is_orthogonal(v1,v2, tol), where v1 and v2 are column vectors of the same size and tol is a scalar value strictly larger than 0. The output should be 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise. 

In [ ]:
def is_orthogonal(v1,v2,tol):
    if len(v1) != len(v2):
        print('column vectors must be of equal size')
    elif tol <= 0:
        print('scalar value must be positive')
    else:
        if abs(0.5*math.pi-angle_between(v1,v2))<tol:
            print
        

In [ ]:
# NO TOUCHY!!!
# Test cases for problem 5
a = np.array([[1], [0.001]])
b = np.array([[0.001], [1]])
# output: 1
is_orthogonal(a,b, 0.01)

# output: 0
is_orthogonal(a,b, 0.001)

# output: 0
a = np.array([[1], [0.001]])
b = np.array([[1], [1]])
is_orthogonal(a,b, 0.01)

# output: 1
a = np.array([[1], [1]])
b = np.array([[-1], [1]])
is_orthogonal(a,b, 1e-10)

##### 6.	Create a class called vector_calculator. __init__ should take self, vector1, and vector2. It should have two methods inside of it that are from problems 1 and 4 above (angle_between and is_orthogonal). Make sure tol is defaulted but can be overwritten. Make sure you can call angle_between and is_orthogonal through the class and return the correct results as in problems 1 and 4. 


#### 7.	Show a graphical representation of the breast cancer data outlined in this reading https://www.datacamp.com/community/tutorials/principal-component-analysis-in-python Be sure to describe what PCA is and incorporate the principal components in your plot. This is just exploratory, so there are many correct answers!
